version: "2"

services:
  app:
    build: ./
    ports:
      - "80:80"
    environment:
      - 'SLACK_WEBHOOK=https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
    volumes:
      - ./app:/app
    command: /start-reload.sh
